# Generated by Django 4.1 on 2023-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('tax_rate', models.FloatField(null=True, verbose_name='tax rate')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['id'],
            },
        ),
    ]
